blank_issues_enabled: true
contact_links:
  - name: I want help with something else
    url: https://discord.gg/Tmn6BKwSnr
    about: Ask your questions about how to achieve a particular effect in Flutter Release X or get help with using a particular API.
